MODELS_PATH: "./output/models"
EXPS_PATH: "./output"

HFLICKR_PATH: "./iHarmony4/HFlickr"
HDAY2NIGHT_PATH: "./iHarmony4/Hday2night"
HCOCO_PATH: "./iHarmony4/HCOCO"
HADOBE5K_PATH: "./iHarmony4/HAdobe5k_resized1024"
HADOBE5K_RS_PATH: "./iHarmony4/HAdobe5k"
HADOBE5K_2048_PATH: "./iHarmony4/HAdobe5k_resized2048"
HADOBE5K_1024_PATH: "./iHarmony4/HAdobe5k_resized1024"
CC_PATH: "./iHarmony4/ccHarmony"
HADOBE5K_4K_PATH: "./iHarmony4/HAdobe5k_select_4k"
HADOBE5K_5K_PATH: "./iHarmony4/HAdobe5k_select_5k"
HADOBE5K_1024_1024_PATH: "./iHarmony4/HAdobe5k_resized1024_1024"
HADOBE5K_2048_2048_PATH: "./iHarmony4/HAdobe5k_resized2048_2048"
